apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: api-gateway

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080
