apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater

metadata:
  name: api-gateway
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: api-gateway
      useAnnotations: true
