replicaCount: 2
image:
  repository: ghcr.io/java-taxi-microservices/api-gateway
  tag: b172fa9c2aa9a0fc2a83bc71c44a9b120f6a7662
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: ghcr-secret
service:
  port: 80
ingress:
  enabled: true
  host: api.alex-antoniuk.dev
