replicaCount: 1
image:
  repository: ghcr.io/java-taxi-microservices/api-gateway
  tag: 84b564ade1a113b9d01345ad7848965d67f0add0
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: ghcr-secret
service:
  port: 80
ingress:
  enabled: true
  host: api.alex-antoniuk.dev
