replicaCount: 2
image:
  repository: ghcr.io/java-taxi-microservices/api-gateway
  tag: b5ea482b36664359ab4c4ed02421db826843d1ae
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: ghcr-secret
service:
  port: 80
ingress:
  enabled: true
  host: api.alex-antoniuk.dev
