apiVersion: apps/v1
kind: Deployment

metadata:
  name: registration-orchestrator

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: registration-orchestrator

  template:
    metadata:
      labels:
        app: registration-orchestrator

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "registration-orchestrator"

        vault.hashicorp.com/agent-inject-secret-application.properties: "secret/data/registration-orchestrator"

        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{`{{- with secret "secret/data/registration-orchestrator" -}}
          spring.datasource.url={{ .Data.data.POSTGRES_URL }}
          spring.datasource.username={{ .Data.data.POSTGRES_USER }}
          spring.datasource.password={{ .Data.data.POSTGRES_PASSWORD }}
          spring.datasource.driver-class-name=org.postgresql.Driver
          {{- end -}}`}}

    spec:
      serviceAccountName: registration-orchestrator

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: registration-orchestrator

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 9090

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profiles.active }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
