apiVersion: v1
kind: Service

metadata:
  name: registration-orchestrator

spec:
  selector:
    app: registration-orchestrator

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: ClusterIP
