replicaCount: 1
image:
  repository: ghcr.io/java-taxi-microservices/registration-orchestrator 
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: ghcr-secret
service:
  port: 9090
  targetPort: 9090
secret:
  postgresUser: postgresUser
  posgresUrl: posgresUrl
  postgresPassword: postgresPassword
