replicaCount: 1
image:
  repository: ghcr.io/java-taxi-microservices/registration-orchestrator
  tag: 9cca6eb62cc5da68fa051648f1b01fb7a474da0b
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: ghcr-secret
service:
  port: 9090
  targetPort: 9090
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
spring:
  profiles:
    active: dev
